<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_Kembali_mdi mdi-arrow-left me-1</name>
   <tag></tag>
   <elementGuidId>40fc8ad8-b518-4471-a3e6-22cede3c7e1f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div[2]/div/div[2]/div/div[2]/div/form/div/div/div[5]/div/button/i</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>i.mdi.mdi-arrow-left.me-1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>73600764-8a9c-4add-a6bb-6be5e6971755</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mdi mdi-arrow-left me-1</value>
      <webElementGuid>28aeec4e-dcf3-4b6a-8cd2-4b160ebc77cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;wrapper&quot;]/div[@class=&quot;content-page&quot;]/div[@class=&quot;content&quot;]/div[@class=&quot;container-fluid&quot;]/div[1]/div[@class=&quot;row&quot;]/div[@class=&quot;col-12&quot;]/form[1]/div[@class=&quot;card&quot;]/div[@class=&quot;card-body&quot;]/div[@class=&quot;justify-content-between row&quot;]/div[@class=&quot;col&quot;]/button[@class=&quot;btn text-muted d-none d-sm-inline-block btn-link fw-semibold&quot;]/i[@class=&quot;mdi mdi-arrow-left me-1&quot;]</value>
      <webElementGuid>3be611dc-7a12-4668-8639-459c18589a2f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[2]/div/div[2]/div/div[2]/div/form/div/div/div[5]/div/button/i</value>
      <webElementGuid>500d20bf-7fce-426e-b4c4-c67668392e03</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/button/i</value>
      <webElementGuid>653550ca-3557-4917-acaf-7781a604beb7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
