<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Upload2 (1)</name>
   <tag></tag>
   <elementGuidId>1a91b1cd-3c35-4e93-b1ea-cc28f5d1e8ff</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div[2]/div/div[2]/div/div[2]/div/div/div/div/div/form/div[2]/div/div/label</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.mb-3.col-md-12 > div > label</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>ab9c8765-82ac-4c60-87e1-a545dc6f10e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>file-upload</value>
      <webElementGuid>b601e18b-28a0-4a9f-84f9-3d4e51c517f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Upload</value>
      <webElementGuid>a6c06cdb-c710-4f80-bc70-31135aeb51ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/div[2]/div[1]/div[2]/div/div[2]/div/div[2]/div/div/div/div/div/form/div[2]/div/div/label/input</value>
      <webElementGuid>f3ec0108-19b8-4232-b549-16b943ea375c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[2]/div/div[2]/div/div[2]/div/div/div/div/div/form/div[2]/div/div/label</value>
      <webElementGuid>ce78efed-579c-4c5c-8c48-2e7b7b75fbb1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Upload Gambar'])[1]/following::label[1]</value>
      <webElementGuid>711bd844-9ef7-4f16-9041-beffcec3f326</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='(max 100 karakter)'])[1]/following::label[2]</value>
      <webElementGuid>b0314757-f908-4804-b0ae-56911819cbfc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Detail Permintaan Pelayanan'])[1]/preceding::label[1]</value>
      <webElementGuid>20d42895-84fd-44ec-8643-09a03648b8aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/label</value>
      <webElementGuid>8e9c0662-931c-42b1-a3eb-56b9f06dd63f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[(text() = 'Upload' or . = 'Upload')]</value>
      <webElementGuid>c4ff20c1-c125-4186-a9b6-89b26c45c8a3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
