<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Permintaan Pelayanan</name>
   <tag></tag>
   <elementGuidId>ca3446b2-6322-416a-b0c8-c455b436ee81</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//ul[@id='main-side-menu']/li[10]/a/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>326664c8-2112-4bf7-8adc-d528c76f03bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Permintaan Pelayanan </value>
      <webElementGuid>c5b7b57a-f0a1-4d8c-b7f3-3e431e7d0bcc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main-side-menu&quot;)/li[@class=&quot;side-nav-item&quot;]/a[@class=&quot;side-nav-link-ref side-sub-nav-link side-nav-link&quot;]/span[1]</value>
      <webElementGuid>64b025ad-76d6-4980-a517-6aa8771306e4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='main-side-menu']/li[10]/a/span</value>
      <webElementGuid>d08f197c-4dfb-4235-8bcc-8d56a9d8d5d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Laporan'])[1]/preceding::span[3]</value>
      <webElementGuid>68d87d8f-7aa1-4a25-88e3-0a6764e21088</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Permintaan Pelayanan']/parent::*</value>
      <webElementGuid>a42fe39f-52d3-4e30-92dd-35916e9726f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[10]/a/span</value>
      <webElementGuid>ec5be753-bfd5-4ba8-acc2-80a66988c4ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = ' Permintaan Pelayanan ' or . = ' Permintaan Pelayanan ')]</value>
      <webElementGuid>2175caa0-6bb2-4bcf-8643-d66fc7776580</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
